import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';

export const THEME = {
  light: {
    background: '#F2F4F1',
    foreground: '#1A211D',
    card: '#FFFFFF',
    cardForeground: '#1A211D',
    popover: '#FFFFFF',
    popoverForeground: '#1A211D',
    primary: '#2D6A4F',
    primaryForeground: '#FDFDFD',
    secondary: '#E4E9E4',
    secondaryForeground: '#234433',
    muted: '#E6E8E5',
    mutedForeground: '#6C776F',
    accent: '#E6E8E5',
    accentForeground: '#234433',
    destructive: '#E5484D',
    border: '#D9DED8',
    input: '#D9DED8',
    ring: '#2D6A4F',
    radius: '0.5rem',
    chart1: '#2D6A4F',
    chart2: '#5CA88C',
    chart3: '#A8C97F',
    chart4: '#4E9673',
    chart5: '#7CB587',
  },
  dark: {
    background: '#191F1B',
    foreground: '#F1F3F0',
    card: '#262E28',
    cardForeground: '#F1F3F0',
    popover: '#262E28',
    popoverForeground: '#F1F3F0',
    primary: '#52A37C',
    primaryForeground: '#121613',
    secondary: '#313B34',
    secondaryForeground: '#F1F3F0',
    muted: '#313B34',
    mutedForeground: '#99A69C',
    accent: '#313B34',
    accentForeground: '#F1F3F0',
    destructive: '#EF7B7B',
    border: 'rgba(255,255,255,0.10)',
    input: 'rgba(255,255,255,0.15)',
    ring: '#52A37C',
    radius: '0.5rem',
    chart1: '#52A37C',
    chart2: '#5CA88C',
    chart3: '#A8C97F',
    chart4: '#4E9673',
    chart5: '#7CB587',
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
